# Wrangler configuration for SuiteSelect website deployment to Cloudflare Workers
name = "suiteselect-website"
compatibility_date = "2025-06-09"

# Static assets configuration for React SPA
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Environment variables
[vars]
NODE_ENV = "production"

# Custom domains (configure in Cloudflare dashboard)
# routes = [
#   { pattern = "suiteselect.com/*", zone_name = "suiteselect.com" },
#   { pattern = "www.suiteselect.com/*", zone_name = "suiteselect.com" }
# ]
